# Generated by Django 4.1.4 on 2023-04-19 00:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='babydogs',
            name='gender',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
