# Generated by Django 4.1.4 on 2023-04-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pups', '0003_rename_quick_description_babydogs_what_includes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='babydogs',
            name='tags',
            field=models.ManyToManyField(blank=True, to='pups.tag'),
        ),
    ]
