# Generated by Django 4.1.4 on 2023-04-21 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pups', '0004_tag_babydogs_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='babydogs',
            name='what_includes',
        ),
    ]
