# Generated by Django 4.1.4 on 2023-04-21 20:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pups', '0005_remove_babydogs_what_includes'),
    ]

    operations = [
        migrations.AddField(
            model_name='babydogs',
            name='price',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
