# Generated by Django 4.1.4 on 2023-05-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pups', '0006_babydogs_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='babydogs',
            name='is_sold',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
